version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=fastapi02
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=hnspo98342ujpfg23476fg23476fgbwswuyfg2763fgusahgfwi7r6tqwfdjwieopop
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=3000

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=fastapi02

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
